### ISSUE TITLE
Horizontal rule breaks the parser

### ISSUE THREAD

**Issue by janbaykara** [andreoliwa/logseq-doctor#55]
## Expected behavior

I'd expect the HR to print as a HR or else be ignored.

## Current behavior

Error is thrown, and STDOUT prints empty.

```python
Traceback (most recent call last):
  File "/Users/janpersonal/.local/bin/lsd", line 8, in <module>
    sys.exit(main())
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/logseq_doctor/cli.py", line 34, in outline
    print(flat_markdown_to_outline(file.read()))
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/logseq_doctor/__init__.py", line 98, in flat_markdown_to_outline
    return mistletoe.markdown(markdown_contents, LogseqRenderer)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/mistletoe/__init__.py", line 21, in markdown
    return renderer.render(Document(iterable))
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/mistletoe/base_renderer.py", line 94, in render
    return self.render_map[token.__class__.__name__](token)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/mistletoe/base_renderer.py", line 204, in render_document
    return self.render_inner(token)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/mistletoe/base_renderer.py", line 109, in render_inner
    return ''.join(map(self.render, token.children))
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/mistletoe/base_renderer.py", line 94, in render
    return self.render_map[token.__class__.__name__](token)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/mistletoe/base_renderer.py", line 201, in render_thematic_break
    return self.render_inner(token)
  File "/Users/janpersonal/.local/pipx/venvs/logseq-doctor/lib/python3.10/site-packages/mistletoe/base_renderer.py", line 109, in render_inner
    return ''.join(map(self.render, token.children))
AttributeError: 'ThematicBreak' object has no attribute 'children'
```

## Steps to reproduce

```markdown
- origin:: Notion

Test

### Heading 1

- Bullet point

Text 

---

### Heading 2

Some text
```

## Your environment

- `logseq-doctor` version used: 0.1.1
- Python version: 3.9.0
- Operating System and version:
- Link to your project:
- Run the following commands and paste the output:

  ```shell script
  which python3
  python3 -V
  pip freeze
  cat $(which flake8)
  ```

```
janpersonal@Jans-MacBook-Pro node % which python3
/usr/local/bin/python3
janpersonal@Jans-MacBook-Pro node % python3 -V
Python 3.9.0
janpersonal@Jans-MacBook-Pro node % pip freeze
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
altgraph==0.10.2
asn1crypto==0.24.0
bdist-mpkg==0.5.0
bonjour-py==0.3
cffi==1.14.3
cryptography==2.9.2
enum34==1.1.6
future==0.17.1
ipaddress==1.0.22
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
py2app==0.7.3
pycparser==2.19
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==19.0.0
pyparsing==2.0.1
python-dateutil==1.5
pytz==2013.7
scipy==0.13.0b1
six==1.12.0
vboxapi==1.0
xattr==0.6.4
janpersonal@Jans-MacBook-Pro node % cat $(which flake8)
cat: flake8: No such file or directory
cat: not: No such file or directory
cat: found: No such file or directory
janpersonal@Jans-MacBook-Pro node % 
```

For more information, see the [CONTRIBUTING](https://github.com/andreoliwa/logseq-doctor/blob/master/CONTRIBUTING.rst) guide.

**Comment by janbaykara** [comment]
Seems to be the same for `-{2,}` and `\*{2,}` regex patterns.

**Comment by andreoliwa** [comment]
Hi, thanks for the report!

This _should_ be fixed by https://github.com/andreoliwa/logseq-doctor/commit/c4c1e1eec1df6c6a33e5b2b47ea9f61114887dcf but I didn't release it yet...

Could you try installing the dev version and tell me if it works?

```
pipx install git+https://github.com/andreoliwa/logseq-doctor
```
